create table sensor_data (
  id bigint generated by default as identity primary key,
  temperature_c float,
  temperature_f float,
  humidity float,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
